package negocio;
// Generated 05/05/2014 19:12:47 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idCliente;
     private Cidade cidade;
     private String nome;
     private String endereco;
     private String numero;
     private String bairro;
     private String complemento;
     private String telFixo;
     private String telCel;
     private String cep;
     private Character tipoCliente;
     private String email;
     private Set pedidos = new HashSet(0);
     private Set pessoafisicas = new HashSet(0);
     private Set pessoajuridicas = new HashSet(0);

    public Cliente() {
    }

    public Cliente(Cidade cidade, String nome, String endereco, String numero, String bairro, String complemento, String telFixo, String telCel, String cep, Character tipoCliente, String email, Set pedidos, Set pessoafisicas, Set pessoajuridicas) {
       this.cidade = cidade;
       this.nome = nome;
       this.endereco = endereco;
       this.numero = numero;
       this.bairro = bairro;
       this.complemento = complemento;
       this.telFixo = telFixo;
       this.telCel = telCel;
       this.cep = cep;
       this.tipoCliente = tipoCliente;
       this.email = email;
       this.pedidos = pedidos;
       this.pessoafisicas = pessoafisicas;
       this.pessoajuridicas = pessoajuridicas;
    }
   
    public Cliente(Cidade cidade, String nome, String endereco, String numero, String bairro, String complemento, String telFixo, String telCel, String cep, Character tipoCliente, String email) {
       this.cidade = cidade;
       this.nome = nome;
       this.endereco = endereco;
       this.numero = numero;
       this.bairro = bairro;
       this.complemento = complemento;
       this.telFixo = telFixo;
       this.telCel = telCel;
       this.cep = cep;
       this.tipoCliente = tipoCliente;
       this.email = email;
    }
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public Cidade getCidade() {
        return this.cidade;
    }
    
    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }
    public String getTelFixo() {
        return this.telFixo;
    }
    
    public void setTelFixo(String telFixo) {
        this.telFixo = telFixo;
    }
    public String getTelCel() {
        return this.telCel;
    }
    
    public void setTelCel(String telCel) {
        this.telCel = telCel;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public Character getTipoCliente() {
        return this.tipoCliente;
    }
    
    public void setTipoCliente(Character tipoCliente) {
        this.tipoCliente = tipoCliente;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }
    public Set getPessoafisicas() {
        return this.pessoafisicas;
    }
    
    public void setPessoafisicas(Set pessoafisicas) {
        this.pessoafisicas = pessoafisicas;
    }
    public Set getPessoajuridicas() {
        return this.pessoajuridicas;
    }
    
    public void setPessoajuridicas(Set pessoajuridicas) {
        this.pessoajuridicas = pessoajuridicas;
    }
    
    @Override
    public String toString() {
        return nome;
    }

    public Object[] toArray() {
            return new Object[]{this, bairro, cidade, telFixo, telCel};
        }  



}


