package negocio;
// Generated 09/07/2014 13:56:11 by Hibernate Tools 3.6.0



/**
 * Configuracoes generated by hbm2java
 */
public class Configuracoes  implements java.io.Serializable {


     private Integer idConfiguracoes;
     private String nomeVendedor;
     private String enderecoVendedor;
     private String telFixoVendedor;
     private String telCelVendedor;
     private String emailVendedor;
     private String emailEnvioPedido;

    public Configuracoes() {
    }

	
    public Configuracoes(String nomeVendedor) {
        this.nomeVendedor = nomeVendedor;
    }
    public Configuracoes(String nomeVendedor, String enderecoVendedor, String telFixoVendedor, String telCelVendedor, String emailVendedor, String emailEnvioPedido) {
       this.nomeVendedor = nomeVendedor;
       this.enderecoVendedor = enderecoVendedor;
       this.telFixoVendedor = telFixoVendedor;
       this.telCelVendedor = telCelVendedor;
       this.emailVendedor = emailVendedor;
       this.emailEnvioPedido = emailEnvioPedido;
    }
   
    public Integer getIdConfiguracoes() {
        return this.idConfiguracoes;
    }
    
    public void setIdConfiguracoes(Integer idConfiguracoes) {
        this.idConfiguracoes = idConfiguracoes;
    }
    public String getNomeVendedor() {
        return this.nomeVendedor;
    }
    
    public void setNomeVendedor(String nomeVendedor) {
        this.nomeVendedor = nomeVendedor;
    }
    public String getEnderecoVendedor() {
        return this.enderecoVendedor;
    }
    
    public void setEnderecoVendedor(String enderecoVendedor) {
        this.enderecoVendedor = enderecoVendedor;
    }
    public String getTelFixoVendedor() {
        return this.telFixoVendedor;
    }
    
    public void setTelFixoVendedor(String telFixoVendedor) {
        this.telFixoVendedor = telFixoVendedor;
    }
    public String getTelCelVendedor() {
        return this.telCelVendedor;
    }
    
    public void setTelCelVendedor(String telCelVendedor) {
        this.telCelVendedor = telCelVendedor;
    }
    public String getEmailVendedor() {
        return this.emailVendedor;
    }
    
    public void setEmailVendedor(String emailVendedor) {
        this.emailVendedor = emailVendedor;
    }
    public String getEmailEnvioPedido() {
        return this.emailEnvioPedido;
    }
    
    public void setEmailEnvioPedido(String emailEnvioPedido) {
        this.emailEnvioPedido = emailEnvioPedido;
    }




}


