package negocio;
// Generated 22/06/2014 16:12:58 by Hibernate Tools 3.6.0



/**
 * KitprodutosId generated by hbm2java
 */
public class KitprodutosId  implements java.io.Serializable {


     private int idProdutoKit;
     private int idProdutoProduto;

    public KitprodutosId() {
    }

    public KitprodutosId(int idProdutoKit, int idProdutoProduto) {
       this.idProdutoKit = idProdutoKit;
       this.idProdutoProduto = idProdutoProduto;
    }
   
    public int getIdProdutoKit() {
        return this.idProdutoKit;
    }
    
    public void setIdProdutoKit(int idProdutoKit) {
        this.idProdutoKit = idProdutoKit;
    }
    public int getIdProdutoProduto() {
        return this.idProdutoProduto;
    }
    
    public void setIdProdutoProduto(int idProdutoProduto) {
        this.idProdutoProduto = idProdutoProduto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof KitprodutosId) ) return false;
		 KitprodutosId castOther = ( KitprodutosId ) other; 
         
		 return (this.getIdProdutoKit()==castOther.getIdProdutoKit())
 && (this.getIdProdutoProduto()==castOther.getIdProdutoProduto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdProdutoKit();
         result = 37 * result + this.getIdProdutoProduto();
         return result;
   }   


}


