package negocio;
// Generated 22/06/2014 16:12:58 by Hibernate Tools 3.6.0



/**
 * Kitprodutos generated by hbm2java
 */
public class Kitprodutos  implements java.io.Serializable {


     private KitprodutosId id;

    public Kitprodutos() {
    }

    public Kitprodutos(KitprodutosId id) {
       this.id = id;
    }
   
    public KitprodutosId getId() {
        return this.id;
    }
    
    public void setId(KitprodutosId id) {
        this.id = id;
    }




}


