package negocio;
// Generated 18/05/2014 14:44:29 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Linha generated by hbm2java
 */
public class Linha  implements java.io.Serializable {


     private Integer idLinha;
     private String nome;
     private String descricao;
     private Set produtos = new HashSet(0);

    public Linha() {
    }

	
    public Linha(String descricao) {
        this.descricao = descricao;
    }
    public Linha(String nome, String descricao, Set produtos) {
       this.nome = nome;
       this.descricao = descricao;
       this.produtos = produtos;
    }
    
    //
    public Linha(String nome, String descricao) {
        this.nome = nome;
        this.descricao = descricao;
    }
    //
   
    public Integer getIdLinha() {
        return this.idLinha;
    }
    
    public void setIdLinha(Integer idLinha) {
        this.idLinha = idLinha;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set produtos) {
        this.produtos = produtos;
    }

    @Override
    public String toString() {
        return nome;
    }
    
    public Object[] toArray() {
        return new Object[]{this, getDescricao()};
    }


}


