package negocio;
// Generated 18/05/2014 14:44:29 by Hibernate Tools 3.6.0



/**
 * PedidoItem generated by hbm2java
 */
public class PedidoItem  implements java.io.Serializable {


     private Integer idPedidoItem;
     private Pedido pedido;
     private Produto produto;
     private Integer quantidade;
     private Float precoTotal;
     // Aqui deveria ter um Float preçoUnitario para saber qual o valor que o usuário colocou na tblProdutosSelecionados

    public PedidoItem() {
    }

    public PedidoItem(Pedido pedido, Produto produto, Integer quantidade, Float precoTotal) {
       this.pedido = pedido;
       this.produto = produto;
       this.quantidade = quantidade;
       this.precoTotal = precoTotal;
    }
    //
    
    //
    
   
    public Integer getIdPedidoItem() {
        return this.idPedidoItem;
    }
    
    public void setIdPedidoItem(Integer idPedidoItem) {
        this.idPedidoItem = idPedidoItem;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public Integer getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(Integer quantidade) {
        this.quantidade = quantidade;
    }
    public Float getPrecoTotal() {
        return this.precoTotal;
    }
    
    public void setPrecoTotal(Float precoTotal) {
        this.precoTotal = precoTotal;
    }

    @Override
    public String toString() {
        return produto.getDescricao();
    }
    public Object[] toArray() {
        return new Object[]{this, produto.getLinha().getDescricao(), produto.getTipoproduto().getDescricao(), produto.getPreco(), quantidade};
    }


}


