package negocio;
// Generated 26/05/2014 20:36:54 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private Integer idPedido;
     private Cliente cliente;
     private String descricao;
     private Float valorTotal;
     private Date data;
     private Set pedidoItems = new HashSet(0);

    public Pedido() {
    }

    public Pedido(Cliente cliente, String descricao, Float valorTotal, Date data, Set pedidoItems) {
       this.cliente = cliente;
       this.descricao = descricao;
       this.valorTotal = valorTotal;
       this.data = data;
       this.pedidoItems = pedidoItems;
    }
   
    //
    public Pedido(Cliente cliente, String descricao) {
        this.cliente = cliente;
        this.descricao = descricao;
        this.data = new Date(System.currentTimeMillis());
    }
    //  
    
    public Integer getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(Integer idPedido) {
        this.idPedido = idPedido;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Float getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(Float valorTotal) {
        this.valorTotal = valorTotal;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Set getPedidoItems() {
        return this.pedidoItems;
    }
    
    public void setPedidoItems(Set pedidoItems) {
        this.pedidoItems = pedidoItems;
    }




}


