package negocio;
// Generated 22/06/2014 16:12:58 by Hibernate Tools 3.6.0



/**
 * Pessoajuridica generated by hbm2java
 */
public class Pessoajuridica  implements java.io.Serializable {


     private int idCliente;
     private Cliente cliente;
     private String cnpj;
     private String ie;

    public Pessoajuridica() {
    }

	
    public Pessoajuridica(Cliente cliente) {
        this.cliente = cliente;
    }
    public Pessoajuridica(Cliente cliente, String cnpj, String ie) {
       this.cliente = cliente;
       this.cnpj = cnpj;
       this.ie = ie;
    }
   
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }
    public String getIe() {
        return this.ie;
    }
    
    public void setIe(String ie) {
        this.ie = ie;
    }




}


