package negocio;
// Generated 05/05/2014 19:12:47 by Hibernate Tools 3.6.0



/**
 * Pessoajuridica generated by hbm2java
 */
public class Pessoajuridica  implements java.io.Serializable {


     private Integer idPessoaJuridica;
     private Cliente cliente;
     private String cnpj;
     private String ie;

    public Pessoajuridica() {
    }

    public Pessoajuridica(Cliente cliente, String cnpj, String ie) {
       this.cliente = cliente;
       this.cnpj = cnpj;
       this.ie = ie;
    }
   
    public Integer getIdPessoaJuridica() {
        return this.idPessoaJuridica;
    }
    
    public void setIdPessoaJuridica(Integer idPessoaJuridica) {
        this.idPessoaJuridica = idPessoaJuridica;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }
    public String getIe() {
        return this.ie;
    }
    
    public void setIe(String ie) {
        this.ie = ie;
    }




}


