package negocio;
// Generated 05/05/2014 19:12:47 by Hibernate Tools 3.6.0



/**
 * Pessoafisica generated by hbm2java
 */
public class Pessoafisica  implements java.io.Serializable {


     private Integer idPessoaFisica;
     private Cliente cliente;
     private String cpf;

    public Pessoafisica() {
    }

    public Pessoafisica(Cliente cliente, String cpf) {
       this.cliente = cliente;
       this.cpf = cpf;
    }
   
    public Integer getIdPessoaFisica() {
        return this.idPessoaFisica;
    }
    
    public void setIdPessoaFisica(Integer idPessoaFisica) {
        this.idPessoaFisica = idPessoaFisica;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }




}


