package negocio;
// Generated 22/06/2014 16:12:58 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


     private Integer idProduto;
     private Tipoproduto tipoproduto;
     private Linha linha;
     private String descricao;
     private float preco;
     private boolean statusVenda;
     private Set pedidoitems = new HashSet(0);
     private Set produtosForIdProdutoProduto = new HashSet(0);
     private Set produtosForIdProdutoKit = new HashSet(0);

    public Produto() {
    }

	
    public Produto(float preco, boolean statusVenda) {
        this.preco = preco;
        this.statusVenda = statusVenda;
    }
    public Produto(Tipoproduto tipoproduto, Linha linha, String descricao, float preco, boolean statusVenda, Set pedidoitems, Set produtosForIdProdutoProduto, Set produtosForIdProdutoKit) {
       this.tipoproduto = tipoproduto;
       this.linha = linha;
       this.descricao = descricao;
       this.preco = preco;
       this.statusVenda = statusVenda;
       this.pedidoitems = pedidoitems;
       this.produtosForIdProdutoProduto = produtosForIdProdutoProduto;
       this.produtosForIdProdutoKit = produtosForIdProdutoKit;
    }
    //
    public Produto(Tipoproduto tipoproduto, Linha linha, String descricao, float preco, boolean statusVenda) {
        this.tipoproduto = tipoproduto;
        this.linha = linha;
        this.descricao = descricao;
        this.preco = preco;
        this.statusVenda = statusVenda;
    }

    public Produto(Integer idProduto, Tipoproduto tipoproduto, Linha linha, String descricao, float preco, boolean statusVenda) {
        this.idProduto = idProduto;
        this.tipoproduto = tipoproduto;
        this.linha = linha;
        this.descricao = descricao;
        this.preco = preco;
        this.statusVenda = statusVenda;
    }
    
    
    //
   
    public Integer getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(Integer idProduto) {
        this.idProduto = idProduto;
    }
    public Tipoproduto getTipoproduto() {
        return this.tipoproduto;
    }
    
    public void setTipoproduto(Tipoproduto tipoproduto) {
        this.tipoproduto = tipoproduto;
    }
    public Linha getLinha() {
        return this.linha;
    }
    
    public void setLinha(Linha linha) {
        this.linha = linha;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public float getPreco() {
        return this.preco;
    }
    
    public void setPreco(float preco) {
        this.preco = preco;
    }
    public boolean isStatusVenda() {
        return this.statusVenda;
    }
    
    public void setStatusVenda(boolean statusVenda) {
        this.statusVenda = statusVenda;
    }
    public Set getPedidoitems() {
        return this.pedidoitems;
    }
    
    public void setPedidoitems(Set pedidoitems) {
        this.pedidoitems = pedidoitems;
    }
    public Set getProdutosForIdProdutoProduto() {
        return this.produtosForIdProdutoProduto;
    }
    
    public void setProdutosForIdProdutoProduto(Set produtosForIdProdutoProduto) {
        this.produtosForIdProdutoProduto = produtosForIdProdutoProduto;
    }
    public Set getProdutosForIdProdutoKit() {
        return this.produtosForIdProdutoKit;
    }
    
    public void setProdutosForIdProdutoKit(Set produtosForIdProdutoKit) {
        this.produtosForIdProdutoKit = produtosForIdProdutoKit;
    }
    @Override
    public String toString() {
        return descricao;
    }
    public Object[] toArray() {
        return new Object[]{this, linha.getNome(), tipoproduto.getDescricao(), this.getPreco()};
    }
    public Object[] toArray2() {
        return new Object[]{this};
    }


}


