package negocio;
// Generated 22/06/2014 13:53:17 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoproduto generated by hbm2java
 */
public class Tipoproduto  implements java.io.Serializable {


     private Integer idTipo;
     private String descricao;
     private String unVenda;
     private Integer porcentagem;
     private Set produtos = new HashSet(0);

    public Tipoproduto() {
    }

    public Tipoproduto(String descricao, String unVenda, Integer porcentagem, Set produtos) {
       this.descricao = descricao;
       this.unVenda = unVenda;
       this.porcentagem = porcentagem;
       this.produtos = produtos;
    }
   
    public Integer getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(Integer idTipo) {
        this.idTipo = idTipo;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getUnVenda() {
        return this.unVenda;
    }
    
    public void setUnVenda(String unVenda) {
        this.unVenda = unVenda;
    }
    public Integer getPorcentagem() {
        return this.porcentagem;
    }
    
    public void setPorcentagem(Integer porcentagem) {
        this.porcentagem = porcentagem;
    }
    public Set getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set produtos) {
        this.produtos = produtos;
    }
    @Override
    public String toString() {
        return descricao;
    }
    
    public Object[] toArray() {
        return new Object[]{this, getUnVenda()};
    }



}


