CREATE DATABASE bioextratus;

USE bioextratus;
show tables;

CREATE TABLE cidade(id_cidade INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT, 
					nome VARCHAR(30) NOT NULL,
					uf CHAR(2) NOT NULL);
					

CREATE TABLE cliente(id_cliente INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT, 
					nome VARCHAR(60),
					endereco VARCHAR(60), 
					numero CHAR(7),
					bairro VARCHAR(60), 
					complemento VARCHAR(60),
					telefone CHAR(15), 
					celular CHAR(15),
					id_cidade INTEGER,
					cep char(9),
					tipo_cliente char(1),
					cpf CHAR(11),
					cnpj CHAR(15), 
					ie CHAR(20),
					email char(40),
					FOREIGN KEY(id_cidade)
					REFERENCES cidade(id_cidade) ON DELETE RESTRICT);



CREATE TABLE linha(
					id_linha INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT, 
					nome VARCHAR(40),
					descricao VARCHAR(100) NOT NULL);
					
CREATE TABLE TIPOPRODUTO(
					id_TIPO INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
					DESCRICAO VARCHAR(60),
					UN_VENDA VARCHAR(10));

CREATE TABLE produto(id_produto INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT, 
					descricao VARCHAR(100),
					preco DECIMAL(5,2) NOT NULL, 
					HABILITADO_VENDA BOOLEAN NOT NULL,
					id_linha INTEGER,

					ID_TIPOPRODUTO INTEGER,

					FOREIGN KEY(id_linha)
					REFERENCES linha(id_linha)ON DELETE RESTRICT,

					FOREIGN KEY(id_TIPOPRODUTO)
					REFERENCES TIPOPRODUTO(id_TIPO)ON DELETE RESTRICT);
					
					
CREATE TABLE pedido(id_pedido INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT, 
					descricao varchar(100),
					valor_total DECIMAL(7,2),
					id_cliente INTEGER,
					data date,
					FOREIGN KEY(id_cliente)
					REFERENCES cliente(id_cliente) ON DELETE RESTRICT);
					
CREATE TABLE pedido_item(id_pedido_item INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
						id_pedido INTEGER,
						id_produto INTEGER,
						quantidade INTEGER, 
						preco_total DECIMAL(7,2),
						FOREIGN KEY(id_pedido)
						REFERENCES pedido(id_pedido) ON DELETE RESTRICT,
						FOREIGN KEY(id_produto)
						REFERENCES produto(id_produto) ON DELETE RESTRICT);


/* inserção de dados*/

INSERT INTO CIDADE (NOME, UF)VALUES('COLATINA','ES');
INSERT INTO CIDADE (NOME, UF)VALUES('RESPLENDOR','MG');
INSERT INTO CIDADE (NOME, UF)VALUES('IBATIBA','ES');
INSERT INTO CIDADE (NOME, UF)VALUES('GOVERNADOR VALADARES','MG');
INSERT INTO CIDADE (NOME, UF)VALUES('VITORIA','ES');

SELECT * FROM CLIENTE;

INSERT INTO CLIENTE( nome, endereco, numero, bairro, complemento, telefone, celular, id_cidade, tipo_cliente, cep, cnpj, ie)VALUES('MEGAMERCADO','PRIMEIRO DE MAIO','93','NORTE',NULL,'3332630000',NULL,2 ,'J','35230000','86874554000133','7927513716514');
INSERT INTO CLIENTE( nome, endereco, numero, bairro, complemento, telefone, celular, id_cidade, tipo_cliente, cep, cnpj, ie)VALUES('VENDAO','AV CASTRO','02','BAIRRO DA VISTA',NULL,'2737229090',NULL,1,'J','29700550','76741456000174','990565157');
INSERT INTO CLIENTE( nome, endereco, numero, bairro, complemento, telefone, celular, id_cidade, tipo_cliente, cep, cnpj, ie)VALUES('FARMAK','PEDRO MAIA', '1008','CENTRO',NULL,'2737225660',NULL,1,'J','35230000','05827315000120','350461562');
INSERT INTO CLIENTE( nome, endereco, numero, bairro, complemento, telefone, celular, id_cidade, tipo_cliente, cep, cnpj, ie)VALUES('TOPS','HENRIQUE BROSTEL', '45','BRASIL NOVO',NULL,'2712432190',NULL,3,'J','29395001','10265444000102','014147807');

INSERT INTO Cliente (nome, endereco, numero, bairro, complemento, telefone, celular, id_cidade, tipo_cliente, cep, cpf)VALUES ('RUAN','EDUARDO MENEGUSSI','93','NORTE','CAMPO DO AMERICA','3332632920','3391321006',2,'F','35230000','11014412044');
INSERT INTO Cliente (nome, endereco, numero, bairro, complemento, telefone, celular, id_cidade, tipo_cliente, cep, cpf)VALUES ('PAULO HENRIQUE','PEDRO EPCHIN','557','COLATINA VELHA','VASCO BAR',NULL,'27999867674',1,'F','28570032','81561643939');

INSERT INTO LINHA(NOME, DESCRICAO)VALUES('VELHA GUARDA','PRODUTOS DESTINADOS A IDOSOS.');
INSERT INTO LINHA(NOME, DESCRICAO)VALUES('SUPER-HEROI','PRODUTOS DESTINADOS A CRIANÇAS.');
INSERT INTO LINHA(NOME, DESCRICAO)VALUES('BEAUTIFUL WOMAN','PRODUTOS DESTINADOS A MULHERES DE 20 A 30 ANOS.');
INSERT INTO LINHA(NOME, DESCRICAO)VALUES('NATURION','PRODUTOS QUE CONSERVAM PROPRIEDADES NATURAIS.');

INSERT INTO TIPOPRODUTO(DESCRICAO, UN_VENDA)VALUES('SHAMPOO','PCT X 12');
INSERT INTO TIPOPRODUTO(DESCRICAO, UN_VENDA)VALUES('CONDICIONADOR','PCT X 12');
INSERT INTO TIPOPRODUTO(DESCRICAO, UN_VENDA)VALUES('SABONETE LIQUIDO','1UN');
INSERT INTO TIPOPRODUTO(DESCRICAO, UN_VENDA)VALUES('CREME','PCT X 12');
INSERT INTO TIPOPRODUTO(DESCRICAO, UN_VENDA)VALUES('FINALIZADOR','UN');

INSERT INTO PRODUTO(descricao, preco, id_linha, ID_TIPOPRODUTO, HABILITADO_VENDA)VALUES('SH FLASH 250ML', 10, 2,1, TRUE);
INSERT INTO PRODUTO(descricao, preco, id_linha, ID_TIPOPRODUTO, HABILITADO_VENDA)VALUES('SH SPIDER MAN 250ML', 10, 2,1, TRUE);
INSERT INTO PRODUTO(descricao, preco, id_linha, ID_TIPOPRODUTO, HABILITADO_VENDA)VALUES('SH BATMAN 250ML', 10, 2,1, TRUE);
INSERT INTO PRODUTO(descricao, preco, id_linha, ID_TIPOPRODUTO, HABILITADO_VENDA)VALUES('SH WOLVERINE 250ML', 10, 2,1, TRUE);
INSERT INTO PRODUTO(descricao, preco, id_linha, ID_TIPOPRODUTO, HABILITADO_VENDA)VALUES('COND FLASH 250ML', 10, 2,2, TRUE);
INSERT INTO PRODUTO(descricao, preco, id_linha, ID_TIPOPRODUTO, HABILITADO_VENDA)VALUES('COND SPIDER MAN 250ML', 10, 2,2, TRUE);
INSERT INTO PRODUTO(descricao, preco, id_linha, ID_TIPOPRODUTO, HABILITADO_VENDA)VALUES('COND BATMAN 250ML', 10, 2,2, TRUE);
INSERT INTO PRODUTO(descricao, preco, id_linha, ID_TIPOPRODUTO, HABILITADO_VENDA)VALUES('COND WOLVERINE 250ML', 10, 2,2, TRUE);

INSERT INTO PRODUTO(descricao, preco, id_linha, ID_TIPOPRODUTO, HABILITADO_VENDA)VALUES('SH VIVENCIAS 250ML', 10, 1,1, TRUE);
INSERT INTO PRODUTO(descricao, preco, id_linha, ID_TIPOPRODUTO, HABILITADO_VENDA)VALUES('COND VIVENCIAS 250ML', 10, 1,2, TRUE);
INSERT INTO PRODUTO(descricao, preco, id_linha, ID_TIPOPRODUTO, HABILITADO_VENDA)VALUES('SH MARIA 250ML', 10, 1,1, TRUE);
INSERT INTO PRODUTO(descricao, preco, id_linha, ID_TIPOPRODUTO, HABILITADO_VENDA)VALUES('COND MARIA 250ML', 10, 1,2, TRUE);

INSERT INTO PRODUTO(descricao, preco, id_linha, ID_TIPOPRODUTO, HABILITADO_VENDA)VALUES('SAB LIQ MAOS 150ML', 19.90, 4,3, TRUE);
INSERT INTO PRODUTO(descricao, preco, id_linha, ID_TIPOPRODUTO, HABILITADO_VENDA)VALUES('SAB LIQ ROSTO 150ML', 39.90, 4,3, TRUE);
INSERT INTO PRODUTO(descricao, preco, id_linha, ID_TIPOPRODUTO, HABILITADO_VENDA)VALUES('SAB LIQ ALCOOL 150ML', 19.90, 4,null, TRUE);

SELECT * FROM PRODUTO;
SELECT * from linha;
